-- 給 Supabase SQL Editor 使用的建立資料表語法

-- 1. 建立人員表
CREATE TABLE staff (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. 建立每日指標表 (細顆粒度儲存)
CREATE TABLE daily_metrics (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  staff_id BIGINT REFERENCES staff(id) ON DELETE CASCADE,
  record_date DATE NOT NULL,
  month_str TEXT NOT NULL, -- 例如 '2026-04'
  care_neuro INTEGER DEFAULT 0,
  care_rehab INTEGER DEFAULT 0,
  new_neuro INTEGER DEFAULT 0,
  new_rehab INTEGER DEFAULT 0,
  new_other INTEGER DEFAULT 0,
  new_beds TEXT[] DEFAULT '{}',
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(staff_id, record_date) -- 確保同一位員工每一天只有一筆獨立紀錄
);

-- 3. 設定權限 (RLS) - 針對這個單純內部的專案，我們暫時允許所有匿名直接讀寫
ALTER TABLE staff ENABLE ROW LEVEL SECURITY;
ALTER TABLE daily_metrics ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read and write on staff"
ON staff FOR ALL USING (true) WITH CHECK (true);

CREATE POLICY "Allow public read and write on daily_metrics"
ON daily_metrics FOR ALL USING (true) WITH CHECK (true);

-- 4. 插入您的 10 位預設人員資料
INSERT INTO staff (id, name) VALUES 
(1, '張小明'), (2, '李大華'), (3, '王阿美'), (4, '陳建國'), (5, '林雅婷'),
(6, '黃志明'), (7, '吳淑芬'), (8, '劉德華'), (9, '蔡依林'), (10, '周杰倫');
